
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh instance-1 --zone=us-west2-a --command='/bin/sh /home/bnatanelic/pull.sh'
